sudo: required
services:
  - docker

before_install:
  - docker build -t couchcat/docker-react-primer -f Dockerfile.dev .

script:
  - docker run -e CI=true couchcat/docker-react-primer npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react-primer"
  env: "DockerReactPrimer-env"
  bucket_name: "elasticbeanstalk-eu-central-1-728154735203" # Found in AWS under S3
  bucket_path: "docker-react-primer" # Currently using the app name
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
